name: Coding Standard & Static Analysis

on:
permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  cs-stan:
    name: Coding Standard & Static Analysis
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, intl
        coverage: none
        tools: phive, cs2pr
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Composer install
      uses: ramsey/composer-install@v3

    - name: Run phpstan
      if: always()
      run: ./vendor/bin/phpstan analyse --error-format=github
